# ----
# Site

title: CSharpRepl
url: "https://fuqua.io/csharprepl"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: 
description: A command line C# REPL with syntax highlighting – explore the language, libraries and nuget packages interactively.
author:
  name: Will Fuqua
  email:
  twitter: # twitter username without the @ symbol
social:
  name: CSharpRepl
  links:
    - https://github.com/waf/CSharpRepl

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

_select_data:
  social_icons:
    - GitHub
